import ParticleText from './effects/ParticleText.jsx'
import ScrollReveal from './effects/ScrollReveal.jsx'
import MoltenMetal from './effects/MoltenMetal.jsx'
import './Abstract.css'

const paragraphs = [
  "EntangleNet is a Hybrid Quantum-Classical Machine Learning framework proposed for intelligent anomaly detection in high-dimensional data generated by critical infrastructure systems. Modern organizations such as industries, financial institutions, healthcare systems, smart grids, and IoT environments continuously generate large volumes of complex operational and network data, making the identification of abnormal and previously unseen patterns increasingly challenging for conventional anomaly detection techniques.",
  "The proposed framework integrates Quantum Feature Encoding, Parameterized Quantum Circuits (PQCs), and a Quantum Convolutional Neural Network (QCNN) with classical machine learning components to learn complex feature representations and identify anomalous behavior. Classical preprocessing and feature engineering are performed before the selected features are encoded into quantum states and processed through the QCNN. The resulting quantum measurements are subsequently passed to classical layers to generate anomaly classifications and risk scores.",
  "In addition to the core detection framework, EntangleNet is designed as a service-oriented anomaly detection platform. It supports both batch-based dataset analysis and continuous monitoring through secure integration mechanisms such as APIs or customer-side data connectors.",
  "The project aims to experimentally investigate the applicability of Hybrid Quantum Machine Learning for anomaly detection and provide a practical architecture for delivering such capabilities as an anomaly-detection service for critical infrastructure environments.",
]

function Abstract() {
  return (
    <section className="abstract">
      <div className="abstract-bg">
        <MoltenMetal
          color1="#4FE3C1"
          color2="#9B6BFF"
          color3="#0A0C14"
          speed={0.2}
          scale={4.5}
          glow={1.2}
          brightness={1.1}
          colorMode="frost"
          grain={true}
          grainIntensity={0.03}
          opacity={0.55}
          mouseInteraction={true}
          mouseStrength={0.2}
        />
      </div>

      <div className="abstract-title">
        <ParticleText
  text="Abstract"
  color="#4FE3C1"
  highlightColor="#9B6BFF"
  fontSize="clamp(4rem, 12vw, 8.5rem)"
  fontWeight={700}
  density={4}
  scatter={160}
  gatherDuration={1500}
  trigger="mount"
/>
      </div>

      <div className="abstract-content glass-panel">
        {paragraphs.map((p, i) => (
            <ScrollReveal
  key={i}
  containerClassName="abstract-reveal"
  textClassName="abstract-reveal-text"
  baseOpacity={0.15}
  baseRotation={2}
  blurStrength={3}
  rotationEnd="bottom top"
  wordAnimationEnd="bottom top"
>
  {p}
</ScrollReveal>
        ))}
      </div>
    </section>
  )
}

export default Abstract